### ISSUE TITLE
The link of "DEMO Python Notebook" in your "delf_enhanced" project is invalid

### ISSUE THREAD

**Issue by yunlongGao23** [insikk/notes#3]
Hello,professer insikk. The link of "DEMO Python Notebook" in your "delf_enhanced" project is invalid. I would be grateful if you could update it. Thanks a lot again! Have a good day!

**Comment by insikk** [comment]
Let me update "delf_enhanced" if I have some time to work on, meanwhile you can refer to https://docs.opencv.org/master/d1/de0/tutorial_py_feature_homography.html 

The example is just using delf feature, but visualization demo logic is mostly the same. (replacing SIFT feature and keypoints to delf feature and keypoints)
